export const info = [
  {id: "chernobyl",genre: "Movie", title:'Chernobyl', img:'/image/Chernobyl.jpg', description:"The events recount the circumstances of the explosion of the Chernobyl nuclear reactor in April 1986 in the Soviet Socialist Union, which became one of the worst human disasters in the twentieth century.", trailer:"www.chernobyl.com", rating:9.4 },
  {id: "cosmos",genre: "Movie", title:'Cosmos', img:'/image/Cosmos.jpg', description:"An exploration of our discovery of the laws of nature and coordinates in space and time.", trailer:"www.cosmos.com", rating:9.3 },
  {id: "mr-robot",genre: "Movie", title:'MR. Robot', img:'/image/MR. ROBOT.jpg', description:"The series tells the story of a young man who suffers from social anxiety disorder. Working as a computer programmer in the morning and a hacker in the evening, he is assigned to work by a mysterious man who calls himself 'Mr. Robot' to infiltrate large corporations they believe are corrupting society.", trailer:"www.mrrobot.com", rating:8.5 },
  {id: "planet-earth",genre: "Movie", title:'Planet Earth', img:'/image/Planet Earth.jpg', description:"Emmy Award-winning, 11 episodes, five years in the making, the most expensive nature documentary series ever commissioned by the BBC, and the first to be filmed in high definition.", trailer:"www.planetearth.com", rating:9.4 },
  {id: "prison-break",genre: "TV Show", title:'Prison Break', img:'/image/Prison Break.jpg', description:"An innocent man is imprisoned and sentenced to death, and his only hope now is in his younger brother, who commits a crime in order to send himself to prison and devises a plan for their escape together, in addition to some other civilians in prison, they encounter a series of interesting and exciting problems and dilemmas, and they try to solve them in order to implement the plan, no matter what it costs them.", trailer:"www.prisonbreak.com", rating:8.3 },
  {id: "roman-empire",genre: "TV Show", title:'Roman Empire', img:'/image/Roman Empire.jpg', description:"Chronicles some of the most famous leaders of the Roman Civilization.", trailer:"www.romanempire.com", rating:10 },
  {id: "the-expanse",genre: "TV Show", title:'The Expanse', img:'/image/The Expanse.jpg', description:"In the 24th century, a disparate band of antiheroes unravel a vast conspiracy that threatens the Solar System's fragile state of cold war.", trailer:"www.theexpanse.com", rating:8.5 },
  {id: "the-walking-dead",genre: "TV Show", title:'The Walking Dead', img:'/image/The Walking Dead.jpg', description:"Police officer (Rick) wakes up from a coma in which he was in for several months as a result of being shot while on the job, to find that the world has been ravaged by the zombies and he is the only survivor. An army of the zombies, events escalate.", trailer:"www.thewalkingdead.com", rating:8.2 },
];